config/routes.rb
DressSharing::Application.routes.draw do
 resources :users
 resources :dresses do
    member do
      get "photo"
    end
  end
 resources :sessions, only: [:create, :new, :destroy]

  match '/signin', to: 'sessions#new'
  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/aboutus', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  root to: 'sessions#new'

end

app/models/body_type.rb
class BodyType <ActiveRecord::Base
  attr_accessible :label
  LABELS = ["Petite", "Athletic", "Lean", "Busty", "Pear", "Tall", "Hourglass", "Curvy"]
  has_many :body_type_dress
  has_many :dresses, :through => :body_type_dresses

end

app/models/body_type_dress.rb
class BodyTypeDress <ActiveRecord::Base
  attr_accessible :dress_id, :body_type_id

  belongs_to :dress
  belongs_to :body_type


end

app/models/dress.rb
class Dress <ActiveRecord::Base
  SIZES = ["0","2","4","6","8","10","12","14+"]
  attr_accessible :body_type_ids, :owner_id, :brand, :color, :size, :notes, :rent, :photo_blob

  belongs_to :owner, :class_name => "User"
  has_many :body_type_dresses
  has_many :body_types, :through => :body_type_dresses
  before_save {|dress| dress.color = dress.color.downcase}

  validates :owner_id, :presence => true
  validates :size, :presence => true
  validates :color, :presence => true
  validates :rent, :presence => true


  def body_types_string
    labels = []
    self.body_types.each do |body_type|
      labels << body_type.label
    end
    labels.join(", ")
  end

  def as_json(options={})
    attributes = super(:only => [:owner_id, :brand, :color, :size, :notes, :rent])
    attributes[:body_type] = self.body_types_string
    attributes
  end
end

app/models/rental.rb
class Rental <ActiveRecord::Base
  attr_accessible :start_date, :end_date, :user_id, :dress_id
  belongs_to :user
  belongs_to :dress

  validates :user_id, :presence => true
  validates :dress_id, :presence => true
  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validate :validate_end_date_before_start_date

  def validate_end_date_before_start_date
    if end_date && start_date
      errors.add(:end_date, "Your start and end date don't make sense") if end_date < start_date
    end
  end

end

app/models/user.rb
class User <ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation, :session_token; :apikey
  attr_protected :points

  has_secure_password

  has_many :dresses, foreign_key: :owner_id
  belongs_to :rental

  before_save { |user| user.email = email.downcase }

  validates :email, :presence => true, uniqueness: {case_sensitive: false},
            format: { with: /\A([^@\s]+)@dartmouth.edu/i, :message => "That is not a valid Dartmouth email."}
  validates :password, :length => { :minimum => 4, :maximum => 20 }, :if => :update_password
  validates :last_name, :presence => true

  def log_out
    self.session_token = nil
  end

  def update_password

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }

  include SessionsHelper

  def current_user
    if session[:sesion_token].nil?
      if params[:apikey].nil?
        nil
      else
        @current_user = User.find_by_apikey(params[:apikey])
      end
    else
      @current_user ||= User.find_by_session_token(session[:sesion_token])
    end
  end

  def require_log_in
    if logged_in?
    else
      redirect_to new_sessions_path
    end
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/dresses_controller.rb
class DressesController < ApplicationController
  before_filter :require_log_in, :except => [:new, :create, :destroy]
  def new
    @dress= Dress.new
  end

  def create
    photo_file = params[:dress].delete(:photo)
    photo_blob = photo_file.nil? ? nil : photo_file.read

    @dress = Dress.new(params[:dress])
    @dress.photo_blob = photo_blob
    @dress.owner_id = session[:current_user_id]

    if @dress.save!
      flash[:notices] = [] unless flash[:notices]
      flash[:notices] << "Your dress is hung in our closet!"
      redirect_to dress_path(@dress)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @dress = Dress.find(params[:dress][:id])
  end

  def destroy
    dress = Dress.find(params[:id])
    dress.destroy
    redirect_to dresses_path
  end

  def index
   @dresses = Dress.all
   respond_to do |format|
      format.html {render :show}
      format.json {render :json => @dresses}
    end
  end

  def show
    @dress = Dress.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render :json => @dress}
    end

  end

  def photo
    dress = Dress.find(params[:id])
    if dress.photo_blob
      send_data dress.photo_blob, :type => 'image/jpg', :disposition => 'inline'
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:user][:email].downcase)
    if @user && @user.authenticate(params[:user][:password])
      @session_token = SecureRandom.base64
      @user.session_token = @session_token
      @user.save!
      session[:current_user_id] = @user.id
      session[:session_token] = @session_token
      redirect_to user_path(@user)
    else
      flash[:error]= "Invalid email/password"
      render 'new'
    end
  end

  def destroy
    @user = User.find_by_session_token(session[:session_token])
    @user.log_out
    session[:session_token] = nil
    session[:current_user_id] = nil
    redirect_to signin_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def contact
end

def about
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user= User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      @user.update_attributes(:session_token => SecureRandom.base64)
      session[:current_user_id] = @user.id
      session[:session_token] = @user.session_token
      @user.apikey = SecureRandom.base64
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(session[:current_user_id])
  end

  def update
    @user = User.find(session[:current_user_id])
  end

  def destroy
    @user = User.find(session[:current_user_id])
  end

  def index
   @users = User.all
  end

  def show
    @user = User.find(session[:current_user_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dresses_helper.rb
module DressesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dresses/_form.html.erb
<p> * Marks mandatory fields. </p>
<%= simple_form_for @dress do |f| %>
  <%= f.input :brand %>
  <%= f.input :color %>
  <%= f.input :size, :label => "Fits like a size X. (I wish Sisterhood of Traveling Pants existed too.)", :item_wrapper_class => 'inline', :collection => Dress::SIZES, :as => :radio_buttons%>
  <br>
  <%= f.association :body_types, :label_method=> :label, :as => :check_boxes%>
  <br>
  <%= f.input :rent, :hint => " No Collis Baked Goods: USD only. (Dresses are rented for 2 days.)" %>
  <br>
  <%= f.file_field :photo %>
  <br>

  <%= f.input :notes, :label => "Notes for the renters. Special instructions. Sentimental memories about that time you wore this to formal and ... Nevermind." %>
  <%= f.button :submit %>
<% end %>

app/views/dresses/edit.html.erb
<% render 'form' %>

app/views/dresses/index.html.erb
<title>The Closet</title>

<h1>The Closet</h1>
<ul>
<% @dresses.each_with_index do |dress, i| %>
    <ul><b>
    <%= link_to "Dress #{i+1} ", dress_path(dress) %></b>
    <small><%= link_to "Edit Dress", edit_dress_path(dress) %></small>
    <li>Brand: <%= dress.brand %></li>
    <li>Color: <%= dress.color %></li>
    <li>Size: <%= dress.size %></li>

    <li>Rental Price: <%= dress.rent %></li>
    <li>Comments: <%= dress.notes %></li>
    </ul>
    <hr>
<% end %>
</ul>

app/views/dresses/show.html.erb
<title> Dress Page</title>
<h2>
<% user = User.find(session[:current_user_id]) %>

    <%= "Dress #{user.dresses.index(@dress)+1}" %>
    </h2>
    <div class='img' ><%= image_tag photo_dress_url(@dress) %></div>
    <ul class='description'>
        <li style="padding-top: 30px">Brand: <%= @dress.brand %></li>
        <li>Color: <%= @dress.color %></li>
        <li>Size: <%= @dress.size %></li>
        <li>Flattering On: <%= @dress.body_types_string %></li>
        <li>Rental Price: <%= @dress.rent %></li>
        <li>Comments: <%= @dress.notes %></li>
    </ul>
<hr style="clear:both;">
<div >
    <p><%= link_to "Edit This Dress", edit_dress_path(@dress) %></p>
    <p><%= link_to "Add A Dress", new_dress_path %></p>
    <p><%= link_to "My Dresses", user_path(User.find(session[:current_user_id])) %></p>
    <p><%= link_to "Delete This Dress", 'dresses#destroy', with: :delete %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DressSharing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

 <div class="container">
    <header class="navbar navbar-inverse">
      <div class="navbar-inner">
        <%= link_to "Whiteboard", signin_path, class: "brand" %>
        <ul class="nav">

          <%if session[:session_token] == nil %>
            <li><%= link_to "Sign-In", signin_path %></li>
          <%else%>
            <li><%= link_to "Sign-Out", signout_path, method: :delete %></li>
          <%end%>

          <li><%= link_to "Home", signin_path %></li>
          <li><%= link_to "About Us", aboutus_path %></li>
          <li><%= link_to "Contact",  contact_path %></li>

          <%if session[:session_token] %>
            <li><%= link_to "My Page", user_path(User.find(session[:current_user_id]))%></li>
            <li><%= link_to "The Closet", dresses_path %></li>
          <% else %>
            <li><%= link_to "Sign-Up", signup_path %></li>
          <%end%>
        </ul>
      </div>
    </header>


  <% if flash[:error] %>
  <div class="alert alert-error"><%= flash[:error] %></div>
  <% end %>

  <% if flash[:success] %>
  <div class="alert alert-success"><%= flash[:success] %></div>
  <% end %>

<%= yield %>

  <footer>
    <hr>
    &copy; {Sassy Hash} 2013
  </footer

</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id= 'error_explanation' %>
    <div class = "alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<title>About Us</title>
<div class ="page-header">
  <h1>{Sassy Hash}
  <small>Smart and Sexy</small></h1>
</div>

<div class = "lead">
  <p> 3 things I strive to be.
  Look Fabulous. Stay On a Budget. Be a Good Person. </p>

  <p><strong> They're not mutually exclusive.<strong></p>

</div>

app/views/static_pages/contact.html.erb
<div class="page-header">
  <h1>Contact Me<br>
    <small>we both know you can't resist it</small></h1>
</div>


<h3>Viable Places</h3>
<ul class = "offset1">
<li><a href= "http://www.twitter.com/brittanyyoon">Twitter</a><br /></li>
<li><a href= "http://www.binnieinsf.tumblr.com">Tumblr</a><br /></li>
<li><a href= "http://www.linkedin.com.binnayoon">Linked-In</a><br /></li>
</ul>
<div style="clear:both;"></div>

app/views/users/new.html.erb
<title>Sign Up</title>
<h1>Sign Up for DressShare<br>
  <small>Look Fabulous on Nickels and Dimes</small></h1>
<hr>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render :partial => 'shared/error_messages', :locals => {:object => @user} %>
      <%= f.label :email, "Dartmouth Email Address" %>
      <%= f.text_field :email %><br>
      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name %><br>
      <%= f.label :last_name, "Last Name" %>
      <%= f.text_field :last_name %><br>
      <%= f.label :password, "Password (4-20 characters)" %>
      <%= f.password_field :password %><br>
      <%= f.label :password_confirmation, "Confirm your password" %>
      <%= f.password_field :password_confirmation %><br>
      <%= f.submit "Create Your Account" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<title>Your Closet</title>
<h1>Hi, <%= @user.first_name %>. Welcome to DressShare.</h1>

<h4>  You have <%= pluralize(@user.dresses.count, "dress") %> in your closet.</h4>

<% if @user.dresses.empty? %>
<% else %>
  <ul>
  <% @user.dresses.each_with_index do |dress, i| %>
    <li>
      <ul><b>
      <%= link_to "Dress #{i+1}", dress_path(dress) %></b>
      <li>Brand: <%= dress.brand %></li>
      <li>Color: <%= dress.color %></li>
      <li>Size: <%= dress.size %></li>
      <li>Flattering On: <%= dress.body_types_string %></li>
      <li>Rental Price: <%= dress.rent %></li>
      <li>Comments: <%= dress.notes %></li>

      <small><%= link_to "Edit Dress", edit_dress_path(dress) %></small>
      </ul>
    </li>
    <hr>
  <% end %>
  </ul>
<% end %>
<br>
<br>
<br>
<div class= row>
<%= link_to "Add A New Dress", new_dress_path %>
<br>
<%= link_to "Rent A Dress", dresses_path %>
</div>

app/views/users/user_errors.html.erb
<% @thing = @user %>
<%= render 'shared/_error_messages' %>